version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./blue-back:/app/blue-back
      - /app/blue-back/node_modules
    ports:
      - "6974:6974"
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.front  # React용 개발 Dockerfile 이름
    volumes:
      - ./blue-front:/app/blue-front
      - /app/blue-front/node_modules
    ports:
      - "4485:4485"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
